import 'package:json_annotation/json_annotation.dart';

part 'MenuItem.g.dart'; // This will be generated by the build_runner

@JsonSerializable() // Add this annotation to your model class
class MenuItem {
  MenuItem({
    this.cost,
    this.name,
    this.description,
    this.image,
    this.order
  });

  int? order;
  String? cost;
  String? name;
  String? description;
  String? image;

  factory MenuItem.fromJson(Map<String, dynamic> json) => _$MenuItemFromJson(json);
  Map<String, dynamic> toJson() => _$MenuItemToJson(this);
}