import 'package:json_annotation/json_annotation.dart';

part 'SectionData.g.dart'; // This will be generated by the build_runner

@JsonSerializable() // Add this annotation to your model class
class SectionData {
  final String? title;
  final String? content;
  final String? subContent;
  final String? buttonTitle;
  final String? imageUrl;
  final String? iconUrl;
  final String? id;
  final int? order;
  SectionData({
    this.title,
    this.content,
    this.subContent,
    this.buttonTitle,
    this.imageUrl,
    this.iconUrl,
    this.id,
    this.order
  });

  factory SectionData.fromJson(Map<String, dynamic> json) => _$SectionDataFromJson(json);
  Map<String, dynamic> toJson() => _$SectionDataToJson(this);

}