// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlzcYBpQcxfYK6Dyi956ZRis9KwFIhGpk',
    appId: '1:428858923828:web:051141814a892504626361',
    messagingSenderId: '428858923828',
    projectId: 'food-order-56bc3',
    authDomain: 'food-order-56bc3.firebaseapp.com',
    storageBucket: 'food-order-56bc3.appspot.com',
    measurementId: 'G-X3WKZH8J9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGnx3fuHilk4nOZQjTqeFOs--K5CZpOXc',
    appId: '1:428858923828:android:07ad8756ffed8d2e626361',
    messagingSenderId: '428858923828',
    projectId: 'food-order-56bc3',
    storageBucket: 'food-order-56bc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUKEmYd2AP7Cx1Ok4ky1SB-uRSBXOMRk',
    appId: '1:428858923828:ios:66c398220f2fa681626361',
    messagingSenderId: '428858923828',
    projectId: 'food-order-56bc3',
    storageBucket: 'food-order-56bc3.appspot.com',
    iosClientId: '428858923828-m04no51gn2vqg8rf4vb5273hqlr2nb76.apps.googleusercontent.com',
    iosBundleId: 'com.example.solmusic',
  );
}
